[package]
name = "execution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.8"
modules = { path = "../modules" }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
dotenv = "0.15.0"
