name: Test

on: [ push, pull_request ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run test
        run: cargo test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run rustfmt
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run check
        run: cargo check
      - name: Run clippy
        run: cargo clippy -- -D warnings
